---

- hosts: local
  gather_facts: False
  vars_files:
    - "group_vars/customer/{{ customer }}.yml"
    - "group_vars/env_type/{{ env_type }}.yml"

  tasks:

    - import_tasks: tasks/create_config.yml
