---
# This playbook deploys an application

- hosts: local
  gather_facts: False
  vars_files:
    - "group_vars/customer/{{ customer }}.yml"
    - "group_vars/env_type/{{ env_type }}.yml"

  tasks:

  - name: deploy new project
    debug: msg="Deploy customer {{ customer }} on {{ env_type }}"
