---

- hosts: local
  gather_facts: False

  tasks:

  - name: Create the project on Openshift
    openshift_raw:
      api_version: v1
      kind: Project
      name: "{{ project_name }}"
      description: "{{ project_description|default(project_display_name)|default(project_name) }}"
      display_name: "{{ project_display_name|default(project_name) }}"
      state: present
