---
# Create endpoints for an app

- name: Print app name
  debug: msg="App name {{ app.name }}"
  tags: route

- name: Make sure application endpoints exist
  openshift_raw:
    force: true
    definition: "{{ lookup('template', item) | from_yaml }}"
    state: present
  with_items: "{{ app | json_query('services[*].templates[]') }}"
  when: item | basename == "ep.yml.j2"
  tags: endpoint
