---
# tasks/set_vars.yml

# TODO :
#  - if apps is not defined or empty, create a minimal "apps" var with objects
#    and vars from the apps/ directory
#  - set vars for apps
- name: List available applications
  find:
    paths: apps
    patterns: "*"
    excludes: "_*"
    file_type: directory
    recurse: no
  register: matching_apps
  when: apps is not defined

- name: Set a flat applications list
  set_fact:
    apps: "{{ matching_apps.files | map(attribute='path') | map('basename') | list }}"
  when: matching_apps is not skipped

- name: Display available apps
  debug: msg="Applications {{ apps }}"

- name: Include customer env_type vars
  include_vars:
    file: "{{ item }}"
  with_items:
    - "group_vars/customer/{{ customer }}.yml"
    - "group_vars/env_type/{{ env_type }}.yml"

- name: Print project details
  debug: msg="Project name {{ project_name }} - domain {{ domain_name }}"
