---
# tasks/set_vars.yml

- name: Lookup applications and set the apps var
  set_fact: apps="{{ lookup('pipe', 'python plugins/utils/lookup_apps.py') | from_yaml }}"

- name: Display looked up applications
  debug: var=apps

- name: Include customer env_type vars
  include_vars:
    file: "{{ item }}"
  with_items:
    - "group_vars/customer/{{ customer }}.yml"
    - "group_vars/env_type/{{ env_type }}.yml"

- name: Print project details
  debug: msg="Project name {{ project_name }} - domain {{ domain_name }}"
