---
should_verify_ssl: false
env_type: staging  # default to be overriden on command line
django_configuration: Staging
customer: patient0  # default to be overriden on command line
project_name: "{{ env_type }}-{{ customer }}"
domain_name: dev.openfun.fr  # default to be overriden on command line
lms_host: "{{ project_name }}-lms.{{ domain_name }}"
cms_host: "{{ project_name }}-cms.{{ domain_name }}"
richie_host: "{{ project_name }}-richie.{{ domain_name }}"

# Ports
django_port:    8000
cms_port:       8081
lms_port:       8071
richie_port:    8061
redirect_port:  8999

nginx_ports:
  - "{{ cms_port }}"
  - "{{ lms_port }}"
  - "{{ richie_port }}"
  - "{{ redirect_port }}"

# External services IPs
mongodb_ip:     192.168.10.11
mysql_ip:       192.168.10.254
postgresql_ip:  192.168.0.1

# Images
edxapp_image:   fundocker/edxapp
edxapp_tag:     ginkgo.1
richie_image:   fundocker/richie
richie_tag:     0.1.0-alpha.3-alpine

# Databases
richie_database:
  host: postgresql-richie
  port: "5432"
  name: richie
  user: fun
  password: pass

# Openshift template files
openshift_deployments:
  # - openshift/edxapp/dc/cms.yml
  # - openshift/edxapp/dc/lms.yml
  # - openshift/edxapp/dc/memcached.yml
  - openshift/common/dc/nginx.yml
  - openshift/richie/dc/postgresql.yml
  - openshift/richie/dc/richie.yml
openshift_endpoints:
  - openshift/common/ep/mongodb.yml
  - openshift/common/ep/mysql.yml
  - openshift/common/ep/postgresql.yml
openshift_jobs:
  # - openshift/edxapp/job/collectstatic_cms.yml
  # - openshift/edxapp/job/collectstatic_lms.yml
  # - openshift/edxapp/job/db_migrate_cms.yml
  # - openshift/edxapp/job/db_migrate_lms.yml
  # - openshift/edxapp/job/update_courses.yml
  - openshift/richie/job/collectstatic.yml
  - openshift/richie/job/db_migrate.yml
  # - openshift/richie/job/regenerate_indexes.yml
openshift_routes:
  # - openshift/common/route/cms.yml
  # - openshift/common/route/lms.yml
  - openshift/common/route/richie.yml
openshift_services:
  - openshift/common/svc/mongodb.yml
  - openshift/common/svc/mysql.yml
  - openshift/common/svc/nginx.yml
  - openshift/common/svc/postgresql.yml
  # - openshift/edxapp/svc/cms.yml
  # - openshift/edxapp/svc/lms.yml
  # - openshift/edxapp/svc/memcached.yml
  - openshift/richie/svc/postgresql.yml
  - openshift/richie/svc/richie.yml
openshift_volumes:
  # - openshift/edxapp/pvc/media.yml
  # - openshift/edxapp/pvc/static.yml
  - openshift/richie/pvc/media.yml
  - openshift/richie/pvc/static.yml
