env_type: staging  # default to be overriden on command line
customer: patient0
project_name: "{{ env_type }}-{{ customer }}"
domain_name: dev.openfun.fr
lms_host: "{{ project_name }}-lms.{{ domain_name }}"
cms_host: "{{ project_name }}-cms.{{ domain_name }}"

# Ports
django_port: 8000
cms_port: 8081
lms_port: 8071

# Images
edxapp_image: edxapp
edxapp_tag: latest
