env_type: staging  # default to be overriden on command line
customer: patient0  # default to be overriden on command line
project_name: "{{ env_type }}-{{ customer }}"
domain_name: dev.openfun.fr
lms_host: "{{ project_name }}-lms.{{ domain_name }}"
cms_host: "{{ project_name }}-cms.{{ domain_name }}"

# Ports
django_port: 8000
cms_port: 8081
lms_port: 8071

# Images
edxapp_image: edxapp
edxapp_tag: latest

# Openshift template files
openshift_base:
  # Volumes
  - openshift/edxapp/pvc/media.yml
  - openshift/edxapp/pvc/static.yml
  # Services
  - openshift/edxapp/svc/cms.yml
  - openshift/edxapp/svc/lms.yml
  - openshift/edxapp/svc/memcached.yml
  - openshift/edxapp/svc/mongodb.yml
  - openshift/edxapp/svc/mysql.yml
  - openshift/edxapp/svc/nginx.yml
  # Deployments
  - openshift/edxapp/dc/cms.yml
  - openshift/edxapp/dc/lms.yml
  - openshift/edxapp/dc/memcached.yml
  - openshift/edxapp/dc/nginx.yml
openshift_databases:
  - openshift/edxapp/ep/mongodb.yml
  - openshift/edxapp/ep/mysql.yml
openshift_jobs:
  - openshift/edxapp/job/collectstatic_cms.yml
  - openshift/edxapp/job/collectstatic_lms.yml
  - openshift/edxapp/job/db_migrate_cms.yml
  - openshift/edxapp/job/db_migrate_lms.yml
  - openshift/edxapp/job/update_courses.yml
openshift_routes:
  - openshift/edxapp/route/cms.yml
  - openshift/edxapp/route/lms.yml
