---
env_type: development  # default to be overriden on command line
customer: patient0  # default to be overriden on command line
project_name: "{{ env_type }}-{{ customer }}"

# Django
django_configuration: Development

# Ports
django_port:    8000
cms_port:       8081
lms_port:       8071
richie_port:    8061
aliases_port:   8999

nginx_ports:
  - "{{ cms_port }}"
  - "{{ lms_port }}"
  - "{{ richie_port }}"
  - "{{ aliases_port }}"

# External services IPs
mongodb_ip:     192.168.10.11
mysql_ip:       192.168.10.254
postgresql_ip:  192.168.0.1

# Images
#
# Service flag should only contain alphanumeric (or '-') characters. It should
# validate the following regexp: '[a-z]([-a-z0-9]*[a-z0-9])?'
elasticsearch_image: "fundocker/openshift-elasticsearch"
elasticsearch_tag:   "6.2.4"
edxapp_image:        "fundocker/edxapp"
edxapp_tag:          "ginkgo.1-1.0.3"
mongodb_image:       "centos/mongodb-32-centos7"
mongodb_tag:         "3.2"
mysql_image:         "centos/mysql-57-centos7"
mysql_tag:           "5.7"
nginx_image:         "fundocker/openshift-nginx"
nginx_tag:           "1.13"
postgresql_image:    "centos/postgresql-96-centos7"
postgresql_tag:      "9.6"
richie_image:        "fundocker/richie"
richie_tag:          "0.1.0-alpha.3-alpine"

# A deployment flag is used to make deployments unique (blue-green strategy).
# This deployment flag should be a lower-case code name containing only
# alpha-numeric characters or dashes. It defaults to "init" and will be
# overriden for each deployment (see deploy.yml playbook).
deployment_stamp: "init"

# We allow multiple versions of the secrets for an application. When defining
# new or modified secrets, you will need to update this value to ensure your DCs
# and jobs point to the relevant version of the secrets for the next deployment.
# Read more about secrets handling in the developers documentation:
# docs/developer_guide/secrets.md
secret_id: "1.0.0"

# Services hosts
richie_host: "{{ project_name }}-richie-{{ deployment_stamp }}.{{ domain_name }}"

# Cluster databases (used for development or feature deployments)
elasticsearch:
  host: "elasticsearch"
  port: "9200"
postgresql:
  host: "postgresql"
  port: "5432"

richie_database:
  host: "{{ postgresql.host }}"
  port: "{{ postgresql.port }}"
  name: richie

# Openshift template files
openshift_deployments:
  - openshift/redirect/dc/nginx.yml
  - openshift/richie/dc/elasticsearch.yml
  - openshift/richie/dc/nginx.yml
  - openshift/richie/dc/richie.yml
openshift_endpoints:
  - openshift/common/ep/postgresql.yml
openshift_jobs:
  - openshift/richie/job/collectstatic.yml
  - openshift/richie/job/db_migrate.yml
  - openshift/richie/job/regenerate_indexes.yml
openshift_routes:
  - openshift/richie/route/richie.yml
 
openshift_services:
  - openshift/common/svc/postgresql.yml
  - openshift/redirect/svc/nginx.yml
  - openshift/richie/svc/elasticsearch.yml
  - openshift/richie/svc/nginx.yml
  - openshift/richie/svc/richie.yml
openshift_volumes:
  - openshift/richie/pvc/media.yml
  - openshift/richie/pvc/static.yml
