# Variables specific to development environments
domain_name: "{{ lookup('env', 'MINISHIFT_IP') }}.nip.io"
django_configuration: Development

# Use development images in the development environment
edxapp_tag: "ginkgo.1-1.0.3-dev"
richie_tag: "0.1.0-alpha.3-alpine-dev"

# Override Openshift template files because databases are containers
# instead of external services reachable via endpoints
openshift_deployments:
  - _common/dc/mongodb.yml
  - _common/dc/mysql.yml
  - _common/dc/postgresql.yml
  - edxapp/dc/cms.yml
  - edxapp/dc/lms.yml
  - edxapp/dc/memcached.yml
  - edxapp/dc/nginx.yml
  - richie/dc/elasticsearch.yml
  - richie/dc/nginx.yml
  - richie/dc/richie.yml
  - redirect/dc/nginx.yml

openshift_endpoints:
    # No endpoints required for the development environment
